### ISSUE TITLE
Undefined symbols _iconv

### ISSUE THREAD

**Issue by waynemystir** [JDevlieghere/LibEBC#1]
Hi @JDevlieghere 

I have followed the build steps in the README. cmake .. works fine. When I run cmake --build . I get the following:

[ 53%] Built target ebc
[ 57%] Linking CXX executable ebctest
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _xmlIconvWrapper in libxml2.a(encoding.o)
  "_iconv_close", referenced from:
      _xmlFindCharEncodingHandler in libxml2.a(encoding.o)
      _xmlCharEncCloseFunc in libxml2.a(encoding.o)
  "_iconv_open", referenced from:
      _xmlFindCharEncodingHandler in libxml2.a(encoding.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test/ebctest] Error 1
make[1]: *** [test/CMakeFiles/ebctest.dir/all] Error 2
make: *** [all] Error 2

But iconv appears to be installed:

which iconv
/usr/local/bin/iconv

Have I not done something correctly here? I appreciate any help you can offer!

Thank you!

**Comment by JDevlieghere** [comment]
Hi Wayne,

Are you building on OSX and did you use Homebrew to install libxml2? If not, what operating system are you using? 

The issue is related to the statically linked version of libxml2, which LibEBC prefers to use over the dynamically linked one. If libxml2 [was configured to use](http://xmlsoft.org/FAQ.html) `iconv` or `libz`, you respectively need the linker flags `-liconv` and `-lz`. Normally CMake takes care of that through `PC_LIBXML_STATIC_LIBRARIES` (see [CMakeLists.txt](https://github.com/JDevlieghere/LibEBC/blob/master/lib/CMakeLists.txt#L64)). 

Can you try removing your build folder and running CMake again with the additional flag `-DBUILD_SHARED_LIBS=False`. This will tell CMake to build and use shared/dynamic libraries for its dependencies. 

Cheers,
Jonas

**Comment by waynemystir** [comment]
Hi Jonas,

Many thanks. I really appreciate your detailed response.

Yes, I am building on OSX and, yes, I did use Homebrew to install libxml2. When I added the additional flag DBUILD_SHARED_LIBS=False, everything worked great.

Cheers & thanks again!

Wayne
